import os
import sys
import xml.etree.ElementTree as ET
from datetime import datetime
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill


def parse_junit_xml(xml_path: str):
    """Parse JUnit XML generated by pytest.

    Returns a list of dicts with keys:
        - test_id (str): classname + method name
        - description (str): test name
        - status (str): 'Passed' or 'Failed'
        - duration (float): execution time in seconds
        - timestamp (str): ISO formatted timestamp of report generation
    """
    tree = ET.parse(xml_path)
    root = tree.getroot()
    results = []
    for testcase in root.iter('testcase'):
        classname = testcase.attrib.get('classname', '')
        name = testcase.attrib.get('name', '')
        time = float(testcase.attrib.get('time', '0'))
        status = 'Passed'
        if testcase.find('failure') is not None or testcase.find('error') is not None:
            status = 'Failed'
        timestamp = datetime.utcnow().isoformat() + 'Z'
        test_id = f"{classname}.{name}" if classname else name
        results.append({
            'test_id': test_id,
            'description': name,
            'status': status,
            'duration': time,
            'timestamp': timestamp,
        })
    return results


def write_excel_report(results, output_path: str):
    wb = Workbook()
    ws = wb.active
    ws.title = "Test Report"
    headers = ["Test ID", "Description", "Status", "Duration (s)", "Timestamp"]
    ws.append(headers)
    # Apply header style
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="4F81BD", end_color="4F81BD", fill_type="solid")
    for col_idx, _ in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center")
    # Data rows
    for row in results:
        ws.append([
            row['test_id'],
            row['description'],
            row['status'],
            round(row['duration'], 3),
            row['timestamp']
        ])
    # Create Summary sheet
    summary_ws = wb.create_sheet(title="Summary")
    # Header
    summary_ws.merge_cells('A1:G1')
    header_cell = summary_ws['A1']
    header_cell.value = "E2E & FUNCTIONAL TESTING REPORT"
    header_cell.font = Font(bold=True, size=14, color="FFFFFF")
    header_cell.alignment = Alignment(horizontal="center")
    header_cell.fill = PatternFill(start_color="003366", end_color="003366", fill_type="solid")
    # Project info
    summary_ws['A3'] = "Project Name"
    summary_ws['B3'] = "Smart Student Platform"
    summary_ws['A4'] = "Execution Date"
    summary_ws['B4'] = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')
    # Determine overall status
    total = len(results)
    failures = sum(1 for r in results if r['status'] == 'Failed')
    passes = total - failures
    summary_ws['A6'] = "Total Test Cases"
    summary_ws['B6'] = total
    summary_ws['A7'] = "Passed"
    summary_ws['B7'] = passes
    summary_ws['A8'] = "Failed"
    summary_ws['B8'] = failures
    # Status cell
    status_cell = summary_ws['A10']
    if failures == 0:
        status_cell.value = "APPROVED"
        status_cell.font = Font(bold=True, color="00FF00")
    else:
        status_cell.value = f"REJECTED - {failures} FAILS"
        status_cell.font = Font(bold=True, color="FF0000")
    # Apply simple styling
    for cell in ['A3','A4','A6','A7','A8','A10']:
        summary_ws[cell].font = Font(bold=True)
    # Continue with existing Test Report sheet as before



def main():
    if len(sys.argv) != 2:
        print("Usage: python report_generator.py <junit_xml_path>")
        sys.exit(1)
    xml_path = sys.argv[1]
    if not os.path.isfile(xml_path):
        print(f"JUnit XML not found: {xml_path}")
        sys.exit(1)
    results = parse_junit_xml(xml_path)
    # Create output directory next to the XML file
    out_dir = os.path.join(os.path.dirname(xml_path), "Excel")
    os.makedirs(out_dir, exist_ok=True)
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    out_file = os.path.join(out_dir, f"E2E_Test_Report_{timestamp}.xlsx")
    write_excel_report(results, out_file)
    # Also generate a summary workbook with status (handled inside write_excel_report)


if __name__ == "__main__":
    main()
