import os
import sys
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill


# ---------------------------------------------------------------------------
# Default paths (relative to selenium_tests/ directory)
# ---------------------------------------------------------------------------
_SCRIPT_DIR = Path(__file__).resolve().parent.parent  # selenium_tests/
_DEFAULT_XML = _SCRIPT_DIR / "Test Results" / "report.xml"
_EXCEL_OUT = _SCRIPT_DIR / "Test Results" / "Excel" / "E2E_Test_Report_SmartStudent_Platform.xlsx"
_SUMMARY_OUT = _SCRIPT_DIR / "Test Results" / "Summary" / "summary.md"


def parse_junit_xml(xml_path: str):
    """Parse JUnit XML generated by pytest.

    Returns a list of dicts with keys:
        - test_id (str): classname + method name
        - description (str): test name
        - status (str): 'Passed' or 'Failed'
        - duration (float): execution time in seconds
        - timestamp (str): ISO formatted timestamp of report generation
    """
    tree = ET.parse(xml_path)
    root = tree.getroot()
    results = []
    for testcase in root.iter('testcase'):
        classname = testcase.attrib.get('classname', '')
        name = testcase.attrib.get('name', '')
        time_val = float(testcase.attrib.get('time', '0'))
        status = 'Passed'
        if testcase.find('failure') is not None or testcase.find('error') is not None:
            status = 'Failed'
        timestamp = datetime.utcnow().isoformat() + 'Z'
        test_id = f"{classname}.{name}" if classname else name
        results.append({
            'test_id': test_id,
            'description': name,
            'status': status,
            'duration': time_val,
            'timestamp': timestamp,
        })
    return results


def write_excel_report(results, output_path: Path):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()
    ws = wb.active
    ws.title = "Test Report"
    headers = ["Test ID", "Description", "Status", "Duration (s)", "Timestamp"]
    ws.append(headers)
    # Apply header style
    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill(start_color="4F81BD", end_color="4F81BD", fill_type="solid")
    for col_idx, _ in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center")
    # Data rows
    for row in results:
        ws.append([
            row['test_id'],
            row['description'],
            row['status'],
            round(row['duration'], 3),
            row['timestamp']
        ])

    # Summary sheet
    summary_ws = wb.create_sheet(title="Summary")
    summary_ws.merge_cells('A1:G1')
    header_cell = summary_ws['A1']
    header_cell.value = "E2E & FUNCTIONAL TESTING REPORT"
    header_cell.font = Font(bold=True, size=14, color="FFFFFF")
    header_cell.alignment = Alignment(horizontal="center")
    header_cell.fill = PatternFill(start_color="003366", end_color="003366", fill_type="solid")

    summary_ws['A3'] = "Project Name"
    summary_ws['B3'] = "Smart Student Platform"
    summary_ws['A4'] = "Execution Date"
    summary_ws['B4'] = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')

    total = len(results)
    failures = sum(1 for r in results if r['status'] == 'Failed')
    passes = total - failures

    summary_ws['A6'] = "Total Test Cases"
    summary_ws['B6'] = total
    summary_ws['A7'] = "Passed"
    summary_ws['B7'] = passes
    summary_ws['A8'] = "Failed"
    summary_ws['B8'] = failures

    status_cell = summary_ws['A10']
    if failures == 0:
        status_cell.value = "APPROVED"
        status_cell.font = Font(bold=True, color="00B050")
    else:
        status_cell.value = f"REJECTED - {failures} FAILS"
        status_cell.font = Font(bold=True, color="FF0000")

    for cell_addr in ['A3', 'A4', 'A6', 'A7', 'A8', 'A10']:
        summary_ws[cell_addr].font = Font(bold=True)

    wb.save(str(output_path))
    print(f"Excel report saved: {output_path}")
    return total, passes, failures


def write_summary_markdown(total, passes, failures, output_path: Path):
    """Write a markdown summary file consumed by the GitHub Actions step summary."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    pass_rate = round(passes / total * 100, 1) if total else 0.0
    status = "✅ APPROVED" if failures == 0 else f"❌ REJECTED — {failures} failure(s)"
    content = f"""# Smart Student Platform — Live E2E Test Report

| Metric | Value |
|--------|-------|
| **Project** | Smart Student Platform |
| **Execution Date** | {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC |
| **Total Tests** | {total} |
| **Passed** | {passes} |
| **Failed** | {failures} |
| **Pass Rate** | {pass_rate}% |
| **Status** | {status} |

> Report generated by `utils/report_generator.py`
"""
    output_path.write_text(content, encoding="utf-8")
    print(f"Summary markdown saved: {output_path}")


def main():
    # Accept optional positional arg for the JUnit XML path; fall back to default
    if len(sys.argv) >= 2:
        xml_path = Path(sys.argv[1])
    else:
        xml_path = _DEFAULT_XML

    if not xml_path.is_file():
        # No XML to parse — generate a zero-result summary so downstream steps don't fail
        print(f"WARNING: JUnit XML not found at {xml_path}. Generating empty summary.")
        total, passes, failures = 0, 0, 0
        write_summary_markdown(total, passes, failures, _SUMMARY_OUT)
        return

    results = parse_junit_xml(str(xml_path))
    total, passes, failures = write_excel_report(results, _EXCEL_OUT)
    write_summary_markdown(total, passes, failures, _SUMMARY_OUT)


if __name__ == "__main__":
    main()
