// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlY15vkdbQUtkeOl9m-Ox4gl0Be-4twJ0',
    appId: '1:323647940211:web:cbeb7317ff1efc30e6ec06',
    messagingSenderId: '323647940211',
    projectId: 'smart-student-platform-fe510',
    authDomain: 'smart-student-platform-fe510.firebaseapp.com',
    storageBucket: 'smart-student-platform-fe510.firebasestorage.app',
    measurementId: 'G-PKN61V3HX0',
    databaseURL:
      'https://smart-student-platform-fe510-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4SVRCmzefWdAUOO_e1afJR8NxWriwRVE',
    appId: '1:323647940211:android:6b43eb9267aa055ce6ec06',
    messagingSenderId: '323647940211',
    projectId: 'smart-student-platform-fe510',
    storageBucket: 'smart-student-platform-fe510.firebasestorage.app',
    databaseURL:
      'https://smart-student-platform-fe510-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOWyo6X9a0HQOtl1nbWgrQHerax1NvNeg',
    appId: '1:323647940211:ios:523f4793970e795de6ec06',
    messagingSenderId: '323647940211',
    projectId: 'smart-student-platform-fe510',
    storageBucket: 'smart-student-platform-fe510.firebasestorage.app',
    iosBundleId: 'com.example.smartStudentPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOWyo6X9a0HQOtl1nbWgrQHerax1NvNeg',
    appId: '1:323647940211:ios:523f4793970e795de6ec06',
    messagingSenderId: '323647940211',
    projectId: 'smart-student-platform-fe510',
    storageBucket: 'smart-student-platform-fe510.firebasestorage.app',
    iosBundleId: 'com.example.smartStudentPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlY15vkdbQUtkeOl9m-Ox4gl0Be-4twJ0',
    appId: '1:323647940211:web:a6b4d0a49555f09fe6ec06',
    messagingSenderId: '323647940211',
    projectId: 'smart-student-platform-fe510',
    authDomain: 'smart-student-platform-fe510.firebaseapp.com',
    storageBucket: 'smart-student-platform-fe510.firebasestorage.app',
    measurementId: 'G-93C9X6WNHR',
  );

}